"""

Revision ID: cc8ba02f10ee
Revises: e57cfaa2bff9
Create Date: 2024-11-28 11:06:08.232600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8ba02f10ee'
down_revision: Union[str, None] = 'e57cfaa2bff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_summary')
    # ### end Alembic commands ###
